{pkgs, inputs, ...}:
with pkgs; [
  pkgs.alejandra
  pkgs.colima
  pkgs.coreutils
  pkgs.curl
  pkgs.docker-buildx
  pkgs.docker-client
  pkgs.dua
  pkgs.eza
  pkgs.git
  pkgs.httpie
  pkgs.jetbrains.datagrip
  pkgs.jless
  pkgs.k9s
  pkgs.kalker
  pkgs.kubectl
  pkgs.kubernetes-helm
  pkgs.morph
  pkgs.mosh
  pkgs.netcat-gnu
  pkgs.nix-direnv
  pkgs.nmap
  pkgs.nodejs
  pkgs.pv
  pkgs.pwgen
  pkgs.pyright
  pkgs.python312
  pkgs.ripgrep
  pkgs.spaceship-prompt
  pkgs.speedtest-cli
  pkgs.terraform
  pkgs.terraform-ls
  pkgs.tree-sitter
  pkgs.vim
  pkgs.wget
  inputs.bwcli.legacyPackages."${pkgs.system}".bitwarden-cli
]
