# Edit this configuration file to define what should be installed on
# your system. Help is available in the configuration.nix(5) man page, on
# https://search.nixos.org/options and in the NixOS manual (`nixos-help`).
{
  config,
  inputs,
  lib,
  pkgs,
  nixos-lima,
  modulesPath,
  ...
}: {
  imports =
    [
      (modulesPath + "/profiles/qemu-guest.nix")
      # The `lima` module sets up systemd services to support LimaVM
      nixos-lima.nixosModules.lima
    ];
  networking.hostName = "nixos";
  networking.useDHCP = true;

  services.lima.enable = true;

  time.timeZone = "Europe/Berlin";

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.stefan = {
    isNormalUser = true;
    extraGroups = ["wheel"];
  };

  # it's just me, so :shrug:
  services.openssh.enable = true;

  security = {
     sudo.wheelNeedsPassword = false;
  };

    # yes, flakes
  nix.settings.experimental-features = ["nix-command" "flakes"];

  # system mounts
  # These settings match the image file generated by the NixOS Lima VM image generator
  boot.loader.grub = {
      device = "nodev";
      efiSupport = true;
      efiInstallAsRemovable = true;
  };
  fileSystems."/boot" = {
      device = lib.mkForce "/dev/vda1";  # /dev/disk/by-label/ESP
      fsType = "vfat";
  };
  fileSystems."/" = {
      device = "/dev/disk/by-label/nixos";
      autoResize = true;
      fsType = "ext4";
      options = [ "noatime" "nodiratime" "discard" ];
  };
    # Host user home directory exposed via Lima virtiofs
    fileSystems."/Users/stefan" = {
      device = "mount0";
      fsType = "virtiofs";
    };

  # misc
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # pkgs
  environment.systemPackages = with pkgs; [
      vim
      git
  ];

  # The usual warnings about changing `stateVersion` apply. Make sure to find and read them
  # before changing this value.
  system.stateVersion = "25.11";
}
