name: Test Nix Darwin Flake on macOS

on:
  pull_request:

jobs:
  build-laptop:
    name: Build Nix Flake for Laptop
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Use Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Flake Inputs
        uses: DeterminateSystems/flake-checker-action@main

      - name: Build Nix Flake
        run: nix run nix-darwin -- build --flake .#Stefan-Keidel-MacBook-Pro

  build-mini:
    name: Build Nix Flake for Mac Mini
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Use Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Flake Inputs
        uses: DeterminateSystems/flake-checker-action@main

      - name: Build Nix Flake
        run: nix run nix-darwin -- build --flake .#mini
